name: Hosts Production
on: [workflow_dispatch]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        cache: true

    - name: Build and Release
      shell: pwsh
      run: |
        Set-Location IronmanPowerShellHost

        $Version = (Get-Content -Raw ./host.manifest.json | ConvertFrom-Json).Version

        New-Item -Path ./version.txt
        Set-Content -Path ./version.txt -Value $Version

        azcopy copy ./version.txt "https://imsreleases.blob.core.windows.net/packager/hosts/version.txt?$($env:PACKAGERSAS)"
        azcopy copy ./host.manifest.json "https://imsreleases.blob.core.windows.net/packager/hosts/$Version/?$($env:PACKAGERSAS)"

        dotnet publish -f net472 -c Release -p:PublishDir=.\publish .\IronmanPowerShellHost.csproj
        azcopy copy ./publish/IronmanPowerShellHost.exe "https://imsreleases.blob.core.windows.net/packager/hosts/$Version/?$($env:PACKAGERSAS)"

        dotnet publish -f net6.0-windows -c Release -p:PublishDir=.\publish -p:AssemblyName=IronmanPowerShellHost-727-Windows -p:UseWindowsForms=true .\IronmanPowerShellHost.csproj
        azcopy copy ./publish/IronmanPowerShellHost-727-Windows.exe "https://imsreleases.blob.core.windows.net/packager/hosts/$Version/?$($env:PACKAGERSAS)"

        dotnet publish -f net6.0 -c Release -p:PublishDir=.\publish -p:AssemblyName=IronmanPowerShellHost-727 .\IronmanPowerShellHost.csproj
        azcopy copy ./publish/IronmanPowerShellHost-727.exe "https://imsreleases.blob.core.windows.net/packager/hosts/$Version/?$($env:PACKAGERSAS)"

        dotnet publish -f net6.0 -c NoPowerShell -p:PublishDir=.\publish -p:AssemblyName=IronmanPowerShellHost-727-NoPowerShell .\IronmanPowerShellHost.csproj
        azcopy copy ./IronmanPowerShellHost/publish/IronmanPowerShellHost-727-NoPowerShell.exe "https://imsreleases.blob.core.windows.net/packager/hosts/$Version/?$($env:PACKAGERSAS)"

        dotnet publish -f net6.0-windows -c NoPowerShell -p:PublishDir=.\publish -p:AssemblyName=IronmanPowerShellHost-727-Windows-NoPowerShell -p:UseWindowsForms=true .\IronmanPowerShellHost.csproj
        azcopy copy ./publish/IronmanPowerShellHost-727-Windows-NoPowerShell.exe "https://imsreleases.blob.core.windows.net/packager/hosts/$Version/?$($env:PACKAGERSAS)"
      env:
        PACKAGERSAS: ${{ secrets.PACKAGERSAS }}