name: Visual Studio

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - uses: actions/cache@v4
      id: cache
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

    - uses: actions/cache@v4
      id: cache2
      with:
        path: .\packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}

    - name: Restore
      shell: pwsh
      if: steps.cache.outputs.cache-hit != 'true' || steps.cache2.outputs.cache-hit != 'true'
      run: |
        dotnet restore PowerShellTools.sln
        nuget restore PowerShellTools.sln

    - name: Image Manifest
      shell: pwsh
      run: |
        $Xml = [Xml](Get-Content .\Build\Common.Build.settings)
        $Version = $Xml.Project.PropertyGroup[1].appveyor_build_version
        .\PowerShellTools\prebuild.ps1 -Version $Version
        .\PowerShellTools.2022\prebuild.ps1 -Version $Version

    - name: Build Ironman Host
      shell: pwsh
      run: |
        Push-Location IronmanPowerShellHost
        dotnet publish -f net472 -c Release .\IronmanPowerShellHost.csproj
        Pop-Location

    - name: Build Extension
      shell: pwsh
      run: |
        $devenv = .\Build\vswhere.exe -latest -property productPath | Split-Path
        msbuild PowerShellTools.sln -p:Configuration=Release -p:Platform="Any CPU" -p:DevEnvDir="$devenv"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PowerShellTools
        path: bin/Release/PowerShellTools.*.vsix