name: VS Code CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        cache: true

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore
      shell: pwsh
      run: |
        dotnet restore PowerShellTools.sln
        nuget restore PowerShellTools.sln

    - name: Build Ironman Host
      shell: pwsh
      run: |
        Push-Location IronmanPowerShellHost
        dotnet publish -f net472 -c Release .\IronmanPowerShellHost.csproj
        Pop-Location

    - name: Build Windows Form Designer
      shell: pwsh
      run: |
        msbuild PowerShellTools.sln -t:rebuild -p:Configuration=Release -p:Platform=x64

    - name: Build
      shell: pwsh
      run: |
        Install-Module InvokeBuild -Scope CurrentUser -Force
        Install-Module PlatyPS -Scope CurrentUser -Force
        Invoke-Build -File .\vscode\vscode.build.ps1
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PowerShellTools
        path: vscode/powershellprotools/kit/powershellprotools-*.vsix